### ISSUE TITLE
changes to environment.yaml file

### ISSUE THREAD

**Issue by galengorski** [USGS-R/drb-estuary-salinity-ml#16]
We need to incorporate the following changes to the environment.yaml file:

- [ ] install the yaml module using `conda install anaconda yaml` so that it is accessible within the anaconda env
- [ ] add the drb_estuary_salinity main repo directory to the pythonpath so that the `utils` module can be loaded. I did this locally by creating a .pth file and adding it to the site-packages directory following [this blog post.](http://evantilton.com/guides/anacondapythonpath/)

**Comment by amsnyder** [comment]
Just to clarify - the second point is just something to do locally right? If so, I think we can close this issue, but maybe @ted80810 will want to set up the second step.

**Comment by galengorski** [comment]
Yeah that's right, I just did this step again once we switched to python 3.8
