### ISSUE TITLE
Fetch multiple NOAA stations

### ISSUE THREAD

**Issue by amsnyder** [USGS-R/drb-estuary-salinity-ml#24]
Add list of NOAA stations from salme's spreadsheet and pull data for each - one file per site

**Comment by amsnyder** [comment]
@ted80810 - maybe this can be the next priority for you to update your code?

**Comment by galengorski** [comment]
Sorry, just getting around to posting which sites I think we should pull. The list on the TOC sheet of [this excel file](https://doimspp.sharepoint.com/:x:/r/sites/usgs-GS-WMA-IWP-PUMP/Shared%20Documents/40.2%20Data-driven%20salinity/Data/DRB-Estuary/Observational_Datasets/DE_Bay_Observations_Table_USGSJuly2021.xlsx?d=w866c9d62e14f4a76b9d2ba6978cef838&csf=1&web=1&e=la5tG4) that Salme shared would be a good start.
![DE_Stations](https://user-images.githubusercontent.com/32860978/146572101-3feb9909-9d49-4c19-abeb-f79b217accc8.PNG)
