### ISSUE TITLE
Fetch other NOAA NOS variables

### ISSUE THREAD

**Issue by amsnyder** [USGS-R/drb-estuary-salinity-ml#25]
Fetch all relevant NOAA NOS variables and store each as a data file

**Comment by galengorski** [comment]
The [excel spreadsheet](https://doimspp.sharepoint.com/:x:/r/sites/usgs-GS-WMA-IWP-PUMP/Shared%20Documents/40.2%20Data-driven%20salinity/Data/DRB-Estuary/Observational_Datasets/DE_Bay_Observations_Table_USGSJuly2021.xlsx?d=w866c9d62e14f4a76b9d2ba6978cef838&csf=1&web=1&e=ydhizo) of data that Salme shared has an initial list of variables for each site that she identifies in the TOC. I think this would be a good start, for most sites it is Water Level, Water Temp, Conductivity (only available at a few sites), Wind Speed, Direction, Relative Humidity, Air Temp
