### ISSUE TITLE
Develop data coverage plots for historical NOAA and USGS

### ISSUE THREAD

**Issue by amsnyder** [USGS-R/drb-estuary-salinity-ml#31]

**Comment by galengorski** [comment]
Just to follow up on this, it would be good to have data coverage at a daily resolution for each NWIS and NOAA site that we are using, and for each variable at that site. For data that is queried at a higher resolution than daily, let's use the variable that we defined in the `munge_config.yaml` file called `prop_obs_required:`. Anything less than this value and we consider that there is no observation recorded for that day for that site variable. Right now that is set to 0.5 which seems like a good starting point, but we can adjust it if this drops out too many days.
